### ISSUE TITLE
Last date to nowcast

### ISSUE THREAD

**Issue by lsbastos** [covid19br/nowcaster#41]
Need to check the last date in the dataset and the last date in the nowcast estimates. It seems they don't match properly.

**Comment by rafalopespx** [comment]
The issue is the default configuration for the package is to calculate the maximum amount of cases within the maximum amount of epidemiological weeks, this is done by the workhorses `data.w` and `data.w_no_age` and subsequent calculations inside the workhorse `nowcasting_inla`, a solution is to give a parameter that can flag which kind of week specification is being used, is it using epiweek or taking the date in a standard manner for weeks.

- [x] logical parameter `epiweek` at `nowcasting_inla`, with default `TRUE` for epiweek usage

**Comment by rafalopespx** [comment]
Fixed at #44
